### ISSUE TITLE
Pipes get broken when water level is reached

### ISSUE THREAD

**Issue by sffc** [paulja/memory-streams-js#10]
If I try to pipe into a WritableStream, if the stream on the other end of the pipe emits a chunk of data that exceeds the high water mark, the WritableStream stops listening to future chunks.  Here is a reproducible test case, where I compare the behavior of this module with another popular module exposing similar functionality, "stream-buffers":

```js
const fs = require("fs");
const memoryStreams = require("memory-streams");
const streamBuffers = require("stream-buffers");

const reader1 = fs.createReadStream("test.jpg");
const writer1 = new (memoryStreams.WritableStream)();
reader1.pipe(writer1);

const reader2 = fs.createReadStream("test.jpg");
const writer2 = new (streamBuffers.WritableStreamBuffer)();
reader2.pipe(writer2);

setTimeout(() => {
	console.log("Bytes in write1 stream: " + writer1.toBuffer().length);
	console.log("Bytes in write2 stream: " + writer2.size());
}, 100);
```

Output:

```
Bytes in write1 stream: 65536
Bytes in write2 stream: 454528
```

In other words, this implementation of WritableStream stops consuming data after it first hits the high water mark, whereas the other implementation finishes reading the entire 454 KB image file.

**Comment by nnnikolay** [comment]
I can confirm the same

**Comment by paulja** [comment]
Hello! As a work-around you can pass in `highWaterMark` with the `options` param when you construct the appropriate stream ([node docs](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_constructor_new_stream_writable_options)). If this does not meet your needs then feel free to create a pull request and I'll happily review and merge in with the project.
