### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by taoqf** [paulja/memory-streams-js#11]
I want upload a file which is a Buffer, so I use this module to transform buffer to a readablestream. 
```ts
// createReadStream could upload file while streams.ReadableStream could not
// const s = fs.createReadStream('./test.jpg');
const s = new streams.ReadableStream(data)

const formData = {
	file: s
};
request.post({
	url,
	formData
}).on('data', (data) => {
	console.log('data===', data.toString('utf8'));
}).on('error', (err) => {
	console.error(err);
})
```
it throws:
```
Error: socket hang up
```
What should I do now ?

**Comment by taoqf** [comment]
MultipartParser.end(): stream ended unexpectedly: state = PART_DATA

**Comment by fatso83** [comment]
This bug should be closed, as this is a user error. This is not how you stream data using the `request` library. Look at the [docs for streaming](https://github.com/request/request#streaming)
