### ISSUE TITLE
How to create a readable stream, that automatically emits EOF after the initial contents?

### ISSUE THREAD

**Issue by stroiman** [paulja/memory-streams-js#14]
When using this library to test some stream-reading functionality, it appears that the `ReadableStream` keeps the stream open, and it's not documented how to tell it when to end the stream.

What I would like to write would be something like this

    const input = new streams.ReadableStream("contents", { allowAppending: false });
    await processStream(input); // resolves when the input stream has been completely processed.

By inspecting the code, I figured that I could call `ReadableStream.append(null)` to simulate EOF. However, if I call this too early, it doesn't work (my stream processing need to attach event handlers first). So I need to wait with calling this until _after_ I created the promise:

    const input = new streams.ReadableStream("contents");
    const processPromise = await processStream(input);
    input.append(null);
    await processPromise;

And since it's not documented, I don't even know if I was ever meant to call it like this.

**Comment by rijnhard** [comment]
Same problem, especially evident when using the `pump` library, and will be same with `streams.pipeline` now added to node core in v10 (which is literally the `pump` library).

**Comment by pludov** [comment]
Same problem here.  The following fix worked for me (just change this._data= ''  into this._data = null)

// Ugggglyyy fix for end of stream 
memory_streams.ReadableStream.prototype._read = function(n) {
    this.push(this._data);
    this._data = null;
  };

**Comment by paulja** [comment]
Please feel free to create a pull request and I’m more than happy to review and include in the project.
