### ISSUE TITLE
TypeScript: Property 'append' does not exist on type 'ReadableStream'

### ISSUE THREAD

**Issue by Jeff-Tian** [paulja/memory-streams-js#16]
Code example:

```
      import memoryStreams = require('memory-streams');
      
      const reader = new memoryStreams.ReadableStream('');
      reader.append('whatever');

```

error:

`error TS2339: Property 'append' does not exist on type 'ReadableStream'.`

**Comment by paulja** [comment]
Thanks for feedback. Please feel free to add a PR to fix, I no longer actively work with Node or in the Node community, so this project exists purely to not break consumers.
