### ISSUE TITLE
write() emits 'drain' before returning, which breaks/confuses Stream API users

### ISSUE THREAD

**Issue by h4l** [paulja/memory-streams-js#18]
When the `WritableStream.write()` method will return `false`, it immediately emits the `'drain'` event _before_ returning. This breaks/confuses stream API users, because:

1. they may receive a drain event before the stream they're writing to has asked them to stop writing
2. they may never receive a drain event, because they start listening for drain _after_ noticing write has returned false.

E.g. the code from the [streams module documentation on `write()`](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback) doesn't work with this module because of reason 2:
```javascript
function write(data, cb) {
  if (!stream.write(data)) {
    stream.once('drain', cb);
  } else {
    process.nextTick(cb);
  }
}
// Wait for cb to be called before doing any other write.
write('hello', () => {
  console.log('Write completed, do more writes now.');
});
```
Indeed, it results in `pipe()` not working correctly, a `'finish'` event is never emitted from `WritableStream` in this example, it fails with the timeout:
```javascript
var assert = require('assert');
var memoryStreams = require('memory-streams');
var stream = require('stream'); // or require('readable-stream')

var timeout = setTimeout(() => {
    assert(false, 'Error: timeout');
}, 1000);

var src = new stream.PassThrough({highWaterMark: 1});
var dest = new memoryStreams.WritableStream({highWaterMark: 1});

dest.on('finish', () => {
    console.log('dest: finish');  // never happens
});
dest.on('close', () => {
    console.log('dest: close');  // never happens
});

stream.pipeline(src, dest, (err) => {
    assert(!err, err);
    console.log('done');
    clearTimeout(timeout);
});

src.write('abcd');
process.nextTick(() => src.end());
```

**Comment by paulja** [comment]
Thanks for feedback. Please feel free to add a PR to fix, I no longer actively work with Node or in the Node community, so this project exists purely to not break consumers.
