### ISSUE TITLE
wither the 0.1.3 release?

### ISSUE THREAD

**Issue by djmitche** [paulja/memory-streams-js#19]
Bizarrely, I was just prompted in https://github.com/taskcluster/taskcluster/pull/3418 to update to memory-streams 0.1.3.  https://www.npmjs.com/package/memory-streams says that was uploaded three years ago.  That may be a renovate bug, I dunno.

But I remain confused about this package and repo:
 * npm says there's a 0.1.3
 * the repo only has a 0.1.2 tag
 * the README in the 0.1.3 claims the package was forked from this repo.. but to where?

This matters because, in the face of so many attacks on the JS ecosystem by compromising small libraries, we all want to be careful what upgrades we take, and the dots don't quite line up here.

If you can help connect the dots, that would help.  If this has indeed been forked and development moved to another repo, please update the README in this repo to point there, and archive this repo.  If it hasn't been forked, please push the commits up to and including the 0.1.3 tag to the repo so we can verify them.  If 0.1.3 really was pushed only recently, please let me know and we can trace down why npm is showing it as 3 years old.

Thanks!

**Comment by paulja** [comment]
Hi! The version of this package is 1.3 and probably has been for more than 3 years (more like 7!) I no longer work in the node space and only keep this repo alive due to the number of people that have a dependency on it. If you would like a change made please feel free to send a PR or fork the repo. Thanks.

**Comment by djmitche** [comment]
Hi @paulja - I asked some questions above.  Do you know the answers?

**Comment by paulja** [comment]
I do not know the answers, the project has been forked several times, I have no responsibly for those. I've not personally touched this project (or Node) for 7 years — what I do know is what I have said above; the project is a 0.1.3; if you're unhappy with the README change it and send a PR or fork it.

**Comment by djmitche** [comment]
@paulja I did send a PR for the README. Would you mind taking a look?
