### ISSUE TITLE
Reading and writing objects

### ISSUE THREAD

**Issue by erelsgl** [paulja/memory-streams-js#3]
Is there a way to write objects, rather than strings?

I am trying to use this stream as a writable-stream in Bunyan:
https://github.com/trentm/node-bunyan#streams
Bunyan writes objects, and I would like to read them as objects. Is this possible?

**Comment by paulja** [comment]
No, sorry, objects won't work natively with this module, they're not really in the spirit of streams and buffers. I have no plans to make this module support objects; however, feel free to fork and I'll happily consider any pull request.
