### ISSUE TITLE
writable.on('finish', cb) doesn't work

### ISSUE THREAD

**Issue by andrewspy** [paulja/memory-streams-js#5]
I am trying to callback when the `writer` is `finish` but can't manage to get it work. Below is the sample code:-

```javascript
function test_optipng() {
  let fs = require('fs');
  let optipng = require('optipng');
  let optimizer = new optipng();
  let streams = require('memory-streams');

  let rs = fs.createReadStream('./testimage.png');
  // let ws = fs.createWriteStream('./testimage.out.png');
  let writer = new streams.WritableStream();

  rs.pipe(optimizer).pipe(writer);

  // ws.on('finish', () => {
  //   console.log('Finished writing file');
  // });

  writer.on('finish', () => {
    console.log(writer.toBuffer().toString('base64'));
    console.log('writer finish');
  });

  // setTimeout(() => {
  //   console.log(writer.toBuffer().toString('base64'));
  // }, 2000);
}

test_optipng();
```

I have tried the `end` event as well without any luck. Thanks!

**Comment by paulja** [comment]
The purpose of this streaming approach is typically for testing and in-memory use-cases, so it's pretty ambiguous as to when it would be appropriate for an end event. Please feel free to have a stab at it tho and send me a PR if you think there is a sensible way to approach it.

**Comment by bruceharris** [comment]
I had the same need. In my tests, I am piping to a writeable stream, and need to verify the content that is piped to it. I switched to https://www.npmjs.com/package/memorystream which supports the `finish` event.
