### ISSUE TITLE
stream.toString() returns object instead of data

### ISSUE THREAD

**Issue by GregOnNet** [paulja/memory-streams-js#9]
Hi,

tried your sample to get data out of a readable stream (see [README.md](https://github.com/paulja/memory-streams-js/blob/master/README.md#usage)).
Unfortuantelly an object is returned when `toString` is called.

Am I missing something to get the sample to work?

I have Node `v7.5.0` installed.

**Expected**

```js
const reader = new streams.ReadableStream('Hello World\n');
console.log(reader.toString()); // outputs: "Hello World\n"
```

**Actual**

```js
const reader = new streams.ReadableStream('Hello World\n');
console.log(reader.toString()); // outputs: [object Object]
```

**Sample I tried**
```js
const streams = require('memory-streams');

// Initialize with the string
const reader = new streams.ReadableStream('Hello World\n');

// Add more data to the stream
reader.append('Hello Universe\n'); // outputs "Hello Universe\n";

// Read the data out
console.log(reader.toString()); // outputs: "Hello World\nHello Universe\n"
```

Many thanks in advance
Greg

**Comment by paulja** [comment]
Hey Greg, there's a typo in the README, missing a call to `read()`. A working sample is shown below:

```
const streams = require('memory-streams')
const reader  = new streams.ReadableStream('Hello World\n')
reader.append('Hello Universe\n')
console.log(reader.read().toString()) // NOTE: the call to `read()`
```

Apologies, a working version was available in the tests and I will update the README.
